### ISSUE TITLE
Problem: I like to change the German translation from "Du" to "Sie" (both "you" in English)

### ISSUE THREAD

**Issue by bikerGP** [Designmodocom/WP-Maintenance-Mode#164]
Hello,
I like to change the German translation from "Du" to "Sie" (both "you" in English). Who can help me with this problem? This is especially needed for things like the subscribe button of the defaul text in the input field for the mail address. I have already searched for the strings in the translation file and manipulated them, for example the "subscribe" button, I changed the German translation from "Abonniere" to "Abonnieren", but nothing changed when I called the maintenance website.
Thanks for your support & best regards,
Matthias

**Comment by georgejipa** [comment]
Hello @bikerGP,

You have 2 solutions:

1. The language files from plugin's directory are used only if there is no translation for that language on wp.org. So... if you need to change the translation, I recommend to suggest the changes on:

https://translate.wordpress.org/projects/wp-plugins/wp-maintenance-mode/stable/de/default

After the changes are approved (by a moderator, not by the author of the plugin), you have to update the language files from "Dashboard" > "Updates".

2. Delete all wp-maintenance-mode-de_DE.* files from /wp-content/languages/plugins/ and this way WordPress will load the language files from plugin's folder. After that you can edit the language file (/plugins/wp-maintenace-mode/languages/wp-maintenance-mode-de_DE.po) using Poedit.

I would recommend to use the first solution because this way the translation will remain even if you update the plugin and will also be useful for other users.

Hint: be sure your "Settings" > "General" > "Site Language" setting is the one you need.

Thanks.

**Comment by wdfee** [comment]
This is the correct link for formal German language translation:
https://translate.wordpress.org/projects/wp-plugins/wp-maintenance-mode/stable/de/formal

@bikerGP just in case you didn't know: you need to set your WordPress installation to German formal. I recommend using the language fallback plugin, too, to use the default "Du"-Files if plugins don't have a formal German version:
https://de.wordpress.org/plugins/language-fallback/
