### ISSUE TITLE
Maintenance mode on woocommerce pages even when logged

### ISSUE THREAD

**Issue by Lilidzeu** [Designmodocom/WP-Maintenance-Mode#171]
Hi everyone ! I don't understand why but I have a problem with the plugin that occurred with no reasons last week while everything was fine and perfect before....
When I'm logged in, I'm supposed to access all my website's pages, right ? So last week.... I couldn't reach the woocommerce-type pages (like product, cart, checkout etc.) and I only could see the maintenance mode. That is weird, especially when it worked before. 
I even tried a restauration of a back up from when it worked and the problem is still there... I don't know what to do... (and by the way, it's the same deal with other maintenance mode plugins..... )

Thank you so much if you have any ideas
Alizée

**Comment by zreedeecom** [comment]
Hi @Lilidzeu if the same problem is appearing with other plugins then I think it is not related with WPMM. First of all clean your browser cache and enable only woocommerce and one manintenance plugin and check if the problem is still there. If not then maybe another plugin is causing the problem, start enabling them one by one until you find the problematic one.

Also enable wordpress debugging mode, maybe that log brings some light..

Regards, Luis.
