### ISSUE TITLE
GDPR, how to integrate it with WP M.M.?

### ISSUE THREAD

**Issue by davideredigital** [Designmodocom/WP-Maintenance-Mode#190]
Good morning, I'm a young Italian WP web developer and I'm a new GitHub member!

I'm creating a Landing Page with this Plugin right now. I would like to collect e-mails through bots and through contact form to warn users when the site is ready and to send them a newsletter after it is complete.
Also, I would like to collect data through the link to my analitycs.
Unfortunately I have no idea how to manage the Privacy Policy for a company.

**_To do all this, how should I set the text of the link to the Privacy Policy to be compatible with the GDPR? Or, which plugin is better to use in conjunction with WP M.M.?_**

_Finally one last question, how can I see a preview of the plugin in development if, by default, it is not visible to the web users?_

I hope You can help me, good work to all!

**Comment by zreedeecom** [comment]
Hi @davideredigital the bot will be saving emails entered by users to your database which you can retrieve using the plugin's panel. If you are not familiar with gdpr I'd highly recommend you to hire some one that can tell you how to get that stuff right because there is no "one size fits all" in terms of legal obligations. Privacy texts might look similar from site to site but they are different.

As far as I know you don't need any extra plugin for showing your are complying with gdpr terms, wordpress integrates the functionality to have your privacy policy clean and WPMM takes care of linking to that page.

About the analytics you can add your tracking id on the settings panel.

To check how WPMM is going to look just enable it and visit the domain using an incognito window for example, that way you don't have to sign out and sign in whenever you want to check your changes.

Regards,
Luis.
