### ISSUE TITLE
Background Style "contain" instead of "Cover"

### ISSUE THREAD

**Issue by nooster2** [Designmodocom/WP-Maintenance-Mode#230]
Hi there.

Is it possible to change the background style from "cover" to "contain"? Maybe there should be an option to change this via dropdown menu in the admin panel.

Thanks

**Comment by georgejipa** [comment]
Hello @nooster2,

You have two options:
1. add your own CSS using the `wpmm_head` hook  ([snippet](https://github.com/WP-Maintenance-Mode/Snippet-Library/blob/540cecc6ac53c9fd7828ed88802e796a8661a54e/add-code-to-head-or-footer.php#L3) - line 3:19)
2. edit `wp-content/plugins/wp-maintenance-mode/assets/css/style.min.css`

I would choose the first option because the change will not be overwritten on future plugin updates.
